In [2]:
import numpy as np

In [10]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [17]:
arr = np.ones([5, 5])
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[4,5,6],[8,79,8]])
arr2

In [21]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.full((2, 2), 7)  # 2x2 array filled with 7


array([[7, 7],
       [7, 7]])

In [24]:
np.eye(4)           # 4x4 identity matrix


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.arange(1, 10, 2) # [1, 3, 5, 7, 9] (like range)


array([1, 3, 5, 7, 9])

In [32]:
np.linspace(0, 1, 2) # [0. 0.25 0.5 0.75 1.] (evenly spaced)

array([0., 1.])

In [36]:
arr = np.array([[10,20,30],[40,50,60]])

print("Shape:", arr.shape)   # (2, 3) → 2 rows, 3 columns
print("Size:", arr.size)     # 6 → total elements
print("Dimensions:", arr.ndim) # 2 → 2D array
print("Data type:", arr.dtype) # int64 (or int32 on Windows)

Shape: (2, 3)
Size: 6
Dimensions: 2
Data type: int64


In [46]:
arr1 = np.array([1,2,3], dtype=np.float32)
print(arr.dtype)

arr_int = arr1.astype(np.int32)
print(arr_int)

float32
[1 2 3]


In [47]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
rr= np.full((4,5),3)
rr

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [10]:
  ast = np.full((4, 6), 8)
  ast.shape

(4, 6)

In [11]:
rr= np.reshape(6, 4)

ValueError: cannot reshape array of size 1 into shape (4,)

In [14]:
arr1 = np.array([[1,2,34], [42,3,3],[4,5,4], [44,5,66]])
arr1.shape


(4, 3)

In [15]:
arr1.reshape(3, 4)

array([[ 1,  2, 34, 42],
       [ 3,  3,  4,  5],
       [ 4, 44,  5, 66]])

In [16]:
arr1.ndim

2

In [23]:
myarr = np.array([[1,2,34], [42,3,3],[4,5,4], [44,5,66]], dtype="float32")

In [24]:
myarr

array([[ 1.,  2., 34.],
       [42.,  3.,  3.],
       [ 4.,  5.,  4.],
       [44.,  5., 66.]], dtype=float32)

In [25]:
myarr.dtype

dtype('float32')

In [27]:
myarr.flatten()

array([ 1.,  2., 34., 42.,  3.,  3.,  4.,  5.,  4., 44.,  5., 66.],
      dtype=float32)