In [1]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [2]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [5]:
flat = arr.flatten()
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [9]:
flat[0:5:2]

array([1, 3, 5])

In [12]:
flat[:5]


array([1, 2, 3, 4, 5])

In [13]:
flat[3:]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [15]:
flat[::2]

array([ 1,  3,  5,  7,  9, 12])

In [16]:
b = flat[3:7]

In [18]:
b[0]


np.int64(4)

In [19]:
b[0] = 44

In [20]:
b

array([44,  5,  6,  7])

In [26]:
flat

array([ 1,  2,  3, 44,  5,  6,  7,  8,  9, 11, 12, 13])

In [22]:
c = flat.copy()

In [25]:
c

array([33333,     2,     3,    44,     5,     6,     7,     8,     9,
          11,    12,    13])

In [24]:
c[0] = 33333

In [27]:
arr3 = np.array([1,54,23,53,2,3,34,5,6,4])
arr3

array([ 1, 54, 23, 53,  2,  3, 34,  5,  6,  4])

In [28]:
arr3[[1,4,6]]

array([54,  2, 34])

In [30]:
arr3[arr3>23]

array([54, 53, 34])

Create a 3x3 array filled with random number and print its shape 

In [41]:
rand = np.random.default_rng()

arrth = rand.random((3,3))

# arr3 = np.array(3,3)
arrth

array([[0.64253655, 0.14595977, 0.36493012],
       [0.21376358, 0.07589069, 0.83206578],
       [0.62745478, 0.42192813, 0.47450149]])

In [42]:
arrth.shape

(3, 3)

Convert an array of float [1.1,2.2,3.3] into integers

In [45]:
float_array = np.array([1.1,2.2,3.3])
float_array

array([1.1, 2.2, 3.3])

In [46]:
# Float to integers?
int_arr = float_array.astype(int)
int_arr

array([1, 2, 3])

Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].


In [64]:
fancy_arr = np.array([1, 2, 3, 4, 5, 6,7,8,9,10])
idx = [1, 3, 5,7,9]
print(fancy_arr[idx])

[ 2  4  6  8 10]


Reshaping & flattening change array structures without copying data.

In [65]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])
arr.shape

(4, 3)

In [69]:
reshape = arr.reshape(3,4)
reshape.shape

(3, 4)

In [71]:
flt_arr = arr.flatten()
flt_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

Reshape a 1D array of size 9 into a 3×3 matrix.


In [75]:
arr3 = np.array([1,54,23,53,2,3,344,55,6])
arr3.shape

(9,)

In [76]:
rArray = arr3.reshape(3,3)
rArray

array([[  1,  54,  23],
       [ 53,   2,   3],
       [344,  55,   6]])

Use boolean masking to filter numbers greater than 50 in an array.


In [79]:
mask = arr3 > 50 
print(arr3[mask])

[ 54  53 344  55]
