# Multidimensional Indexing and Axis

In [1]:
import numpy as np

In [44]:
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
np.sum(arr, axis=0)


array([12, 15, 18])

In [10]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [11]:
print(arr[0, ])

3


In [15]:
arr[0][2]

np.int64(3)

In [16]:
arr[0:2, 1:]

array([[2, 3],
       [5, 6]])

In [20]:
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [21]:
arr[0:2][1:3]

array([[4, 5, 6]])

In [23]:
arr3d = np.array([
    [[1,2,3], [4,5,6]],
                 [[7,8,9], [10,11,12]]
                 ])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [24]:
arr3d.shape

(2, 2, 3)

In [25]:
arr3d[0,1,2]

np.int64(6)

In [26]:
arr3d[:, 0, :]

array([[1, 2, 3],
       [7, 8, 9]])

In [27]:
arr3d[:, 0, :] = 1

In [28]:
arr3d

array([[[ 1,  1,  1],
        [ 4,  5,  6]],

       [[ 1,  1,  1],
        [10, 11, 12]]])

In [49]:
arr[:, 1] = 3
arr

array([[  0,   3, 888],
       [  0,   3,   6],
       [  0,   3,   9]])

In [55]:
arr[2, :] =7
arr


array([[888, 888, 888],
       [  2,   2,   2],
       [  7,   7,   7]])

In [56]:
arr[0, :] = 888
arr

array([[888, 888, 888],
       [  2,   2,   2],
       [  7,   7,   7]])