# Broadcasting in NumPy
Now, we'll explore how to make your code faster with vectorization and broadcasting in NumPy. These techniques are key to boosting performance in numerical operations by avoiding slow loops and memory inefficiency.

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
result = arr ** 2
result

array([ 1,  4,  9, 16, 25])

In [4]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])
 
result = arr1 + arr2  # Element-wise addition
print(result)  # Output: [11 22 33]

[11 22 33]


In [5]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])
 
result = arr1 + arr2  # Broadcasting arr2 across arr1
print(result)
# Output:
# [[2 4 6]
#  [5 7 9]]

[[2 4 6]
 [5 7 9]]


In [6]:
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])
 
# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)
 
# Normalizing the data using broadcasting
normalized_data = (data - mean) / std
 
print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]


In [8]:
mean = data.mean(axis=0)
mean

array([20., 30., 40.])

In [9]:
std = data.std(axis=0)
std

array([7.07106781, 7.07106781, 7.07106781])

In [15]:
normalized_data = (data - mean) / std
normalized_data

array([[-1.41421356, -1.41421356, -1.41421356],
       [-0.70710678, -0.70710678, -0.70710678],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.70710678,  0.70710678,  0.70710678],
       [ 1.41421356,  1.41421356,  1.41421356]])