# Built in Mathematical Functions in NumPy

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])

In [3]:
np.mean(arr)

np.float64(2.5)

In [4]:
np.median(arr)

np.float64(2.5)

In [5]:
np.std(arr)

np.float64(1.118033988749895)

In [6]:
np.var(arr)

np.float64(1.25)

In [7]:
np.min(arr)

np.int64(1)

In [8]:
np.max(arr)

np.int64(4)

In [14]:
np.power(arr, 2)

array([ 1,  4,  9, 16])

In [15]:
np.sum(arr)

np.int64(10)

In [13]:
np.prod(arr)

np.int64(24)

In [16]:
np.median(arr)

np.float64(2.5)

In [17]:
np.percentile(arr, 50)  # For the 50th percentile (median)

np.float64(2.5)

In [18]:
np.argmin(arr)

np.int64(0)

In [19]:
np.argmax(arr)

np.int64(3)

In [25]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,9])
np.corrcoef(arr1, arr2)

array([[1.        , 0.98270763],
       [0.98270763, 1.        ]])

In [26]:
np.unique(arr)

array([1, 2, 3, 4])

In [27]:
np.diff(arr)

array([1, 1, 1])

In [28]:
np.cumsum(arr)


array([ 1,  3,  6, 10])

In [29]:
np.linspace(0, 10, 5)  # 5 numbers from 0 to 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [30]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [31]:
np.exp(arr)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])